import Head from 'next/head'
import styles from '/styles/Home.module.scss'
import profiles from '/info/profile.json'
import { useRouter } from 'next/router'
import React, { useRef } from 'react'
import { useReactToPrint } from 'react-to-print';
import Resume from '/components/resume'

export default function Home() {
  const router = useRouter();
  const componentRef = useRef();
  const {profile, draft} = router.query;
  const handlePrint = useReactToPrint({
    content: () => componentRef.current,
  });

  if (!profiles[profile]) {
    return <></>
  }
  return (
    <div className={styles.container}>
      <Head>
        <title>{profiles[profile].fullName}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.bufferSpace}>
      <Resume profile={profiles[profile]} draft={draft} ref={componentRef} />
      </div>

      <footer className={styles.footer}>
          <button onClick={handlePrint}>Print this out!</button>
      </footer>
    </div>
  )
}
