import Head from 'next/head'
import Image from 'next/image'
import styles from '/styles/Home.module.scss'
import Experience from '/components/experience'
import Header from '/components/header'
import profiles from '/info/profile.json'
import { useRouter } from 'next/router'

export default function Home() {
  const router = useRouter();
  const {profile, draft} = router.query;
  console.log(profiles, profiles[profile]);
  if (!profiles[profile]) {
    return <></>
  }
  const {fullName, title, linkedin, location, phone, subprofile} = profiles[profile];
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Header fullName={fullName} title={title} linkedin={linkedin} location={location} phone={phone} />
        <Experience experiences={subprofile[draft].experience} />
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
